# -*- coding: utf-8 -*-
"""Argentina Provincial Data.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IsC00_Lix6r1MmnobdbjgII3w1pRvXGU
"""

# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

datos = pd.read_csv('argentina.csv')

po= datos.sort_values(by='poverty')

po.head(5)

po.tail(5)

do= datos.sort_values(by='doctors_per_cap')

do.tail(5)

do.head(5)

nuse=datos['province']

co=nuse.loc[2]
fo=nuse.loc[7]
sa=nuse.loc[15]
san=nuse.loc[17]
sal=nuse.loc[18]

provincias = co,fo,sa,san,sal
provincias